---
# (string) Timezone for the servers
timezone: "America/Vancouver"

# (list) Additional ssh public keys to add to the nodes
# ssh_authorized_keys:

fedora:
  packages:
    - dnf-plugin-system-upgrade
    - dnf-utils
    - hdparm
    - htop
    - ipvsadm
    - lm_sensors
    - nano
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-libselinux
    - python3-pyyaml
    - intel-media-va-driver-non-free
    - intel-opencl-icd

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
    - intel-media-va-driver-non-free
    - intel-opencl-icd
