---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Etc/UTC"
  KUBE_VIP_ADDR: "192.168.50.15"
  METALLB_LB_RANGE: "192.168.50.5-192.168.50.14"
  METALLB_K8S_GATEWAY_ADDR: "192.168.50.6"
  METALLB_INGRESS_ADDR: "192.168.50.5"
